### ISSUE TITLE
Differences with jupyter-fs

### ISSUE THREAD

**Issue by timkpaine** [jtpio/jupyterlab-filesystem#3]
Just wanted to note that this seems to overlap in functionality quite considerably with https://github.com/jpmorganchase/jupyter-fs

**Comment by jtpio** [comment]
Thanks @timkpaine for bringing that up :+1: 

The main motivation for this extension is to give access to local files in JupyterLite (tracked in https://github.com/jupyterlite/jupyterlite/issues/403).

It is using the (non-standard) FileSystem API from the browsers: https://developer.mozilla.org/en-US/docs/Web/API/Window/showOpenFilePicker. Which is for now not supported in Firefox.

Does `jupyter-fs` support this? And does it work without a Python backend?

Probably we could rename this repository to something else, that indicates more clearly this is using browser APIs only.

**Comment by timkpaine** [comment]
@jtpio makes sense, sounds like the overlap was in name only. I highly doubt that `jupyter-fs` will work without a python backend (for now), but the goals behind `jupyter-fs` are just to provide a unified and generic contents manager interface (filesystem-like, trending towards fsspec) and allow you to open multiple of them. So in that respect there is overlap, but not as much as the name overlap suggested.
